//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTransaction.OAHrmServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserBean", Namespace="http://webservice.hrm.weaver")]
    [System.SerializableAttribute()]
    public partial class UserBean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int accounttypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string assistantidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bememberdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bepartydateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string birthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string certificatenumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string createdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string degreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departmentcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departmentidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departmentnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float dsporderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string educationlevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enddateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string folkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string healthinfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string heightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string homeaddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string islabouunionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobactivitydescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobactivityidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobcallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobgroupidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string joblevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobtitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastChangdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string manageridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maritalstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobilecallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nativeplaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string policyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string regresidentplaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string residentplaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string seclevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subcompanycodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subcompanyid1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subcompanynameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string systemlanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tempresidentnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int useridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string weightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string workcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string workroomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int accounttype {
            get {
                return this.accounttypeField;
            }
            set {
                if ((this.accounttypeField.Equals(value) != true)) {
                    this.accounttypeField = value;
                    this.RaisePropertyChanged("accounttype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string assistantid {
            get {
                return this.assistantidField;
            }
            set {
                if ((object.ReferenceEquals(this.assistantidField, value) != true)) {
                    this.assistantidField = value;
                    this.RaisePropertyChanged("assistantid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bememberdate {
            get {
                return this.bememberdateField;
            }
            set {
                if ((object.ReferenceEquals(this.bememberdateField, value) != true)) {
                    this.bememberdateField = value;
                    this.RaisePropertyChanged("bememberdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bepartydate {
            get {
                return this.bepartydateField;
            }
            set {
                if ((object.ReferenceEquals(this.bepartydateField, value) != true)) {
                    this.bepartydateField = value;
                    this.RaisePropertyChanged("bepartydate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string birthday {
            get {
                return this.birthdayField;
            }
            set {
                if ((object.ReferenceEquals(this.birthdayField, value) != true)) {
                    this.birthdayField = value;
                    this.RaisePropertyChanged("birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string certificatenum {
            get {
                return this.certificatenumField;
            }
            set {
                if ((object.ReferenceEquals(this.certificatenumField, value) != true)) {
                    this.certificatenumField = value;
                    this.RaisePropertyChanged("certificatenum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string createdate {
            get {
                return this.createdateField;
            }
            set {
                if ((object.ReferenceEquals(this.createdateField, value) != true)) {
                    this.createdateField = value;
                    this.RaisePropertyChanged("createdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string degree {
            get {
                return this.degreeField;
            }
            set {
                if ((object.ReferenceEquals(this.degreeField, value) != true)) {
                    this.degreeField = value;
                    this.RaisePropertyChanged("degree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departmentcode {
            get {
                return this.departmentcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentcodeField, value) != true)) {
                    this.departmentcodeField = value;
                    this.RaisePropertyChanged("departmentcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departmentid {
            get {
                return this.departmentidField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentidField, value) != true)) {
                    this.departmentidField = value;
                    this.RaisePropertyChanged("departmentid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departmentname {
            get {
                return this.departmentnameField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentnameField, value) != true)) {
                    this.departmentnameField = value;
                    this.RaisePropertyChanged("departmentname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float dsporder {
            get {
                return this.dsporderField;
            }
            set {
                if ((this.dsporderField.Equals(value) != true)) {
                    this.dsporderField = value;
                    this.RaisePropertyChanged("dsporder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string educationlevel {
            get {
                return this.educationlevelField;
            }
            set {
                if ((object.ReferenceEquals(this.educationlevelField, value) != true)) {
                    this.educationlevelField = value;
                    this.RaisePropertyChanged("educationlevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string enddate {
            get {
                return this.enddateField;
            }
            set {
                if ((object.ReferenceEquals(this.enddateField, value) != true)) {
                    this.enddateField = value;
                    this.RaisePropertyChanged("enddate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                if ((object.ReferenceEquals(this.faxField, value) != true)) {
                    this.faxField = value;
                    this.RaisePropertyChanged("fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string folk {
            get {
                return this.folkField;
            }
            set {
                if ((object.ReferenceEquals(this.folkField, value) != true)) {
                    this.folkField = value;
                    this.RaisePropertyChanged("folk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string healthinfo {
            get {
                return this.healthinfoField;
            }
            set {
                if ((object.ReferenceEquals(this.healthinfoField, value) != true)) {
                    this.healthinfoField = value;
                    this.RaisePropertyChanged("healthinfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string height {
            get {
                return this.heightField;
            }
            set {
                if ((object.ReferenceEquals(this.heightField, value) != true)) {
                    this.heightField = value;
                    this.RaisePropertyChanged("height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string homeaddress {
            get {
                return this.homeaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.homeaddressField, value) != true)) {
                    this.homeaddressField = value;
                    this.RaisePropertyChanged("homeaddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string islabouunion {
            get {
                return this.islabouunionField;
            }
            set {
                if ((object.ReferenceEquals(this.islabouunionField, value) != true)) {
                    this.islabouunionField = value;
                    this.RaisePropertyChanged("islabouunion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobactivitydesc {
            get {
                return this.jobactivitydescField;
            }
            set {
                if ((object.ReferenceEquals(this.jobactivitydescField, value) != true)) {
                    this.jobactivitydescField = value;
                    this.RaisePropertyChanged("jobactivitydesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobactivityid {
            get {
                return this.jobactivityidField;
            }
            set {
                if ((object.ReferenceEquals(this.jobactivityidField, value) != true)) {
                    this.jobactivityidField = value;
                    this.RaisePropertyChanged("jobactivityid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobcall {
            get {
                return this.jobcallField;
            }
            set {
                if ((object.ReferenceEquals(this.jobcallField, value) != true)) {
                    this.jobcallField = value;
                    this.RaisePropertyChanged("jobcall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobgroupid {
            get {
                return this.jobgroupidField;
            }
            set {
                if ((object.ReferenceEquals(this.jobgroupidField, value) != true)) {
                    this.jobgroupidField = value;
                    this.RaisePropertyChanged("jobgroupid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string joblevel {
            get {
                return this.joblevelField;
            }
            set {
                if ((object.ReferenceEquals(this.joblevelField, value) != true)) {
                    this.joblevelField = value;
                    this.RaisePropertyChanged("joblevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobtitle {
            get {
                return this.jobtitleField;
            }
            set {
                if ((object.ReferenceEquals(this.jobtitleField, value) != true)) {
                    this.jobtitleField = value;
                    this.RaisePropertyChanged("jobtitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastChangdate {
            get {
                return this.lastChangdateField;
            }
            set {
                if ((object.ReferenceEquals(this.lastChangdateField, value) != true)) {
                    this.lastChangdateField = value;
                    this.RaisePropertyChanged("lastChangdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string locationid {
            get {
                return this.locationidField;
            }
            set {
                if ((object.ReferenceEquals(this.locationidField, value) != true)) {
                    this.locationidField = value;
                    this.RaisePropertyChanged("locationid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginid {
            get {
                return this.loginidField;
            }
            set {
                if ((object.ReferenceEquals(this.loginidField, value) != true)) {
                    this.loginidField = value;
                    this.RaisePropertyChanged("loginid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string managerid {
            get {
                return this.manageridField;
            }
            set {
                if ((object.ReferenceEquals(this.manageridField, value) != true)) {
                    this.manageridField = value;
                    this.RaisePropertyChanged("managerid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maritalstatus {
            get {
                return this.maritalstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.maritalstatusField, value) != true)) {
                    this.maritalstatusField = value;
                    this.RaisePropertyChanged("maritalstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileField, value) != true)) {
                    this.mobileField = value;
                    this.RaisePropertyChanged("mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobilecall {
            get {
                return this.mobilecallField;
            }
            set {
                if ((object.ReferenceEquals(this.mobilecallField, value) != true)) {
                    this.mobilecallField = value;
                    this.RaisePropertyChanged("mobilecall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nativeplace {
            get {
                return this.nativeplaceField;
            }
            set {
                if ((object.ReferenceEquals(this.nativeplaceField, value) != true)) {
                    this.nativeplaceField = value;
                    this.RaisePropertyChanged("nativeplace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string policy {
            get {
                return this.policyField;
            }
            set {
                if ((object.ReferenceEquals(this.policyField, value) != true)) {
                    this.policyField = value;
                    this.RaisePropertyChanged("policy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string regresidentplace {
            get {
                return this.regresidentplaceField;
            }
            set {
                if ((object.ReferenceEquals(this.regresidentplaceField, value) != true)) {
                    this.regresidentplaceField = value;
                    this.RaisePropertyChanged("regresidentplace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string residentplace {
            get {
                return this.residentplaceField;
            }
            set {
                if ((object.ReferenceEquals(this.residentplaceField, value) != true)) {
                    this.residentplaceField = value;
                    this.RaisePropertyChanged("residentplace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string seclevel {
            get {
                return this.seclevelField;
            }
            set {
                if ((object.ReferenceEquals(this.seclevelField, value) != true)) {
                    this.seclevelField = value;
                    this.RaisePropertyChanged("seclevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sex {
            get {
                return this.sexField;
            }
            set {
                if ((object.ReferenceEquals(this.sexField, value) != true)) {
                    this.sexField = value;
                    this.RaisePropertyChanged("sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startdate {
            get {
                return this.startdateField;
            }
            set {
                if ((object.ReferenceEquals(this.startdateField, value) != true)) {
                    this.startdateField = value;
                    this.RaisePropertyChanged("startdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subcompanycode {
            get {
                return this.subcompanycodeField;
            }
            set {
                if ((object.ReferenceEquals(this.subcompanycodeField, value) != true)) {
                    this.subcompanycodeField = value;
                    this.RaisePropertyChanged("subcompanycode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subcompanyid1 {
            get {
                return this.subcompanyid1Field;
            }
            set {
                if ((object.ReferenceEquals(this.subcompanyid1Field, value) != true)) {
                    this.subcompanyid1Field = value;
                    this.RaisePropertyChanged("subcompanyid1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subcompanyname {
            get {
                return this.subcompanynameField;
            }
            set {
                if ((object.ReferenceEquals(this.subcompanynameField, value) != true)) {
                    this.subcompanynameField = value;
                    this.RaisePropertyChanged("subcompanyname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string systemlanguage {
            get {
                return this.systemlanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.systemlanguageField, value) != true)) {
                    this.systemlanguageField = value;
                    this.RaisePropertyChanged("systemlanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telephone {
            get {
                return this.telephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.telephoneField, value) != true)) {
                    this.telephoneField = value;
                    this.RaisePropertyChanged("telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tempresidentnumber {
            get {
                return this.tempresidentnumberField;
            }
            set {
                if ((object.ReferenceEquals(this.tempresidentnumberField, value) != true)) {
                    this.tempresidentnumberField = value;
                    this.RaisePropertyChanged("tempresidentnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userid {
            get {
                return this.useridField;
            }
            set {
                if ((this.useridField.Equals(value) != true)) {
                    this.useridField = value;
                    this.RaisePropertyChanged("userid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weight {
            get {
                return this.weightField;
            }
            set {
                if ((object.ReferenceEquals(this.weightField, value) != true)) {
                    this.weightField = value;
                    this.RaisePropertyChanged("weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string workcode {
            get {
                return this.workcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.workcodeField, value) != true)) {
                    this.workcodeField = value;
                    this.RaisePropertyChanged("workcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string workroom {
            get {
                return this.workroomField;
            }
            set {
                if ((object.ReferenceEquals(this.workroomField, value) != true)) {
                    this.workroomField = value;
                    this.RaisePropertyChanged("workroom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentBean", Namespace="http://webservice.hrm.weaver")]
    [System.SerializableAttribute()]
    public partial class DepartmentBean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _canceledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _departmentidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _fullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _shortnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _showorderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _subcompanyidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _supdepartmentidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string actionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastChangdateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _canceled {
            get {
                return this._canceledField;
            }
            set {
                if ((object.ReferenceEquals(this._canceledField, value) != true)) {
                    this._canceledField = value;
                    this.RaisePropertyChanged("_canceled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _code {
            get {
                return this._codeField;
            }
            set {
                if ((object.ReferenceEquals(this._codeField, value) != true)) {
                    this._codeField = value;
                    this.RaisePropertyChanged("_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _departmentid {
            get {
                return this._departmentidField;
            }
            set {
                if ((object.ReferenceEquals(this._departmentidField, value) != true)) {
                    this._departmentidField = value;
                    this.RaisePropertyChanged("_departmentid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _fullname {
            get {
                return this._fullnameField;
            }
            set {
                if ((object.ReferenceEquals(this._fullnameField, value) != true)) {
                    this._fullnameField = value;
                    this.RaisePropertyChanged("_fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _shortname {
            get {
                return this._shortnameField;
            }
            set {
                if ((object.ReferenceEquals(this._shortnameField, value) != true)) {
                    this._shortnameField = value;
                    this.RaisePropertyChanged("_shortname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _showorder {
            get {
                return this._showorderField;
            }
            set {
                if ((object.ReferenceEquals(this._showorderField, value) != true)) {
                    this._showorderField = value;
                    this.RaisePropertyChanged("_showorder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _subcompanyid {
            get {
                return this._subcompanyidField;
            }
            set {
                if ((object.ReferenceEquals(this._subcompanyidField, value) != true)) {
                    this._subcompanyidField = value;
                    this.RaisePropertyChanged("_subcompanyid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _supdepartmentid {
            get {
                return this._supdepartmentidField;
            }
            set {
                if ((object.ReferenceEquals(this._supdepartmentidField, value) != true)) {
                    this._supdepartmentidField = value;
                    this.RaisePropertyChanged("_supdepartmentid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string action {
            get {
                return this.actionField;
            }
            set {
                if ((object.ReferenceEquals(this.actionField, value) != true)) {
                    this.actionField = value;
                    this.RaisePropertyChanged("action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastChangdate {
            get {
                return this.lastChangdateField;
            }
            set {
                if ((object.ReferenceEquals(this.lastChangdateField, value) != true)) {
                    this.lastChangdateField = value;
                    this.RaisePropertyChanged("lastChangdate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobTitleBean", Namespace="http://webservice.hrm.weaver")]
    [System.SerializableAttribute()]
    public partial class JobTitleBean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _departmentidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _fullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _jobcompetencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _jobdocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _jobresponsibilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _jobtitleidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _jobtitleremarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _lastChangdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _shortnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string actionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _code {
            get {
                return this._codeField;
            }
            set {
                if ((object.ReferenceEquals(this._codeField, value) != true)) {
                    this._codeField = value;
                    this.RaisePropertyChanged("_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _departmentid {
            get {
                return this._departmentidField;
            }
            set {
                if ((object.ReferenceEquals(this._departmentidField, value) != true)) {
                    this._departmentidField = value;
                    this.RaisePropertyChanged("_departmentid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _fullname {
            get {
                return this._fullnameField;
            }
            set {
                if ((object.ReferenceEquals(this._fullnameField, value) != true)) {
                    this._fullnameField = value;
                    this.RaisePropertyChanged("_fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _jobcompetency {
            get {
                return this._jobcompetencyField;
            }
            set {
                if ((object.ReferenceEquals(this._jobcompetencyField, value) != true)) {
                    this._jobcompetencyField = value;
                    this.RaisePropertyChanged("_jobcompetency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _jobdoc {
            get {
                return this._jobdocField;
            }
            set {
                if ((object.ReferenceEquals(this._jobdocField, value) != true)) {
                    this._jobdocField = value;
                    this.RaisePropertyChanged("_jobdoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _jobresponsibility {
            get {
                return this._jobresponsibilityField;
            }
            set {
                if ((object.ReferenceEquals(this._jobresponsibilityField, value) != true)) {
                    this._jobresponsibilityField = value;
                    this.RaisePropertyChanged("_jobresponsibility");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _jobtitleid {
            get {
                return this._jobtitleidField;
            }
            set {
                if ((object.ReferenceEquals(this._jobtitleidField, value) != true)) {
                    this._jobtitleidField = value;
                    this.RaisePropertyChanged("_jobtitleid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _jobtitleremark {
            get {
                return this._jobtitleremarkField;
            }
            set {
                if ((object.ReferenceEquals(this._jobtitleremarkField, value) != true)) {
                    this._jobtitleremarkField = value;
                    this.RaisePropertyChanged("_jobtitleremark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _lastChangdate {
            get {
                return this._lastChangdateField;
            }
            set {
                if ((object.ReferenceEquals(this._lastChangdateField, value) != true)) {
                    this._lastChangdateField = value;
                    this.RaisePropertyChanged("_lastChangdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _shortname {
            get {
                return this._shortnameField;
            }
            set {
                if ((object.ReferenceEquals(this._shortnameField, value) != true)) {
                    this._shortnameField = value;
                    this.RaisePropertyChanged("_shortname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string action {
            get {
                return this.actionField;
            }
            set {
                if ((object.ReferenceEquals(this.actionField, value) != true)) {
                    this.actionField = value;
                    this.RaisePropertyChanged("action");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="anyType2anyTypeMap", Namespace="http://localhost/services/HrmService", ItemName="entry")]
    [System.SerializableAttribute()]
    public class anyType2anyTypeMap : System.Collections.Generic.List<TestTransaction.OAHrmServiceReference.entry> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entry", Namespace="http://localhost/services/HrmService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.anyType2anyTypeMap))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.UserBean[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.UserBean))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.DepartmentBean[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.DepartmentBean))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.JobTitleBean[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.JobTitleBean))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.SubCompanyBean[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.SubCompanyBean))]
    public partial class entry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object keyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object key {
            get {
                return this.keyField;
            }
            set {
                if ((object.ReferenceEquals(this.keyField, value) != true)) {
                    this.keyField = value;
                    this.RaisePropertyChanged("key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubCompanyBean", Namespace="http://webservice.hrm.weaver")]
    [System.SerializableAttribute()]
    public partial class SubCompanyBean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _canceledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _fullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _shortnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _showorderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _subcompanyidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _supsubcompanyidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _websiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string actionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastChangdateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _canceled {
            get {
                return this._canceledField;
            }
            set {
                if ((object.ReferenceEquals(this._canceledField, value) != true)) {
                    this._canceledField = value;
                    this.RaisePropertyChanged("_canceled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _code {
            get {
                return this._codeField;
            }
            set {
                if ((object.ReferenceEquals(this._codeField, value) != true)) {
                    this._codeField = value;
                    this.RaisePropertyChanged("_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _fullname {
            get {
                return this._fullnameField;
            }
            set {
                if ((object.ReferenceEquals(this._fullnameField, value) != true)) {
                    this._fullnameField = value;
                    this.RaisePropertyChanged("_fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _shortname {
            get {
                return this._shortnameField;
            }
            set {
                if ((object.ReferenceEquals(this._shortnameField, value) != true)) {
                    this._shortnameField = value;
                    this.RaisePropertyChanged("_shortname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _showorder {
            get {
                return this._showorderField;
            }
            set {
                if ((object.ReferenceEquals(this._showorderField, value) != true)) {
                    this._showorderField = value;
                    this.RaisePropertyChanged("_showorder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _subcompanyid {
            get {
                return this._subcompanyidField;
            }
            set {
                if ((object.ReferenceEquals(this._subcompanyidField, value) != true)) {
                    this._subcompanyidField = value;
                    this.RaisePropertyChanged("_subcompanyid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _supsubcompanyid {
            get {
                return this._supsubcompanyidField;
            }
            set {
                if ((object.ReferenceEquals(this._supsubcompanyidField, value) != true)) {
                    this._supsubcompanyidField = value;
                    this.RaisePropertyChanged("_supsubcompanyid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _website {
            get {
                return this._websiteField;
            }
            set {
                if ((object.ReferenceEquals(this._websiteField, value) != true)) {
                    this._websiteField = value;
                    this.RaisePropertyChanged("_website");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string action {
            get {
                return this.actionField;
            }
            set {
                if ((object.ReferenceEquals(this.actionField, value) != true)) {
                    this.actionField = value;
                    this.RaisePropertyChanged("action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastChangdate {
            get {
                return this.lastChangdateField;
            }
            set {
                if ((object.ReferenceEquals(this.lastChangdateField, value) != true)) {
                    this.lastChangdateField = value;
                    this.RaisePropertyChanged("lastChangdate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/services/HrmService", ConfigurationName="OAHrmServiceReference.HrmServicePortType")]
    public interface HrmServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string SynSubCompany(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> SynSubCompanyAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getPropValue(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getPropValueAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getHrmSubcompanyInfoXML(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getHrmSubcompanyInfoXMLAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        TestTransaction.OAHrmServiceReference.UserBean[] getHrmUserInfo(string in0, string in1, string in2, string in3, string in4, string in5);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<TestTransaction.OAHrmServiceReference.UserBean[]> getHrmUserInfoAsync(string in0, string in1, string in2, string in3, string in4, string in5);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        TestTransaction.OAHrmServiceReference.DepartmentBean[] getHrmDepartmentInfo(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<TestTransaction.OAHrmServiceReference.DepartmentBean[]> getHrmDepartmentInfoAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getHrmUserInfoXML(string in0, string in1, string in2, string in3, string in4, string in5);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getHrmUserInfoXMLAsync(string in0, string in1, string in2, string in3, string in4, string in5);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        bool checkUser(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<bool> checkUserAsync(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        TestTransaction.OAHrmServiceReference.JobTitleBean[] getHrmJobTitleInfo(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<TestTransaction.OAHrmServiceReference.JobTitleBean[]> getHrmJobTitleInfoAsync(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        bool changeUserPassword(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<bool> changeUserPasswordAsync(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        TestTransaction.OAHrmServiceReference.anyType2anyTypeMap LoadTemplateProp(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<TestTransaction.OAHrmServiceReference.anyType2anyTypeMap> LoadTemplatePropAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string SynDepartment(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> SynDepartmentAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.anyType2anyTypeMap))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.UserBean[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.UserBean))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.DepartmentBean[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.DepartmentBean))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.JobTitleBean[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.JobTitleBean))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.SubCompanyBean[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.SubCompanyBean))]
        void writeLog1(string in0, object in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task writeLog1Async(string in0, object in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string SynJobtitle(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> SynJobtitleAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.anyType2anyTypeMap))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.UserBean[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.UserBean))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.DepartmentBean[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.DepartmentBean))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.JobTitleBean[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.JobTitleBean))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.SubCompanyBean[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TestTransaction.OAHrmServiceReference.SubCompanyBean))]
        void writeLog(object in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task writeLogAsync(object in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getClientIpXfire();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getClientIpXfireAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string SynHrmResource(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> SynHrmResourceAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        TestTransaction.OAHrmServiceReference.SubCompanyBean[] getHrmSubcompanyInfo(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<TestTransaction.OAHrmServiceReference.SubCompanyBean[]> getHrmSubcompanyInfoAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getHrmJobTitleInfoXML(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getHrmJobTitleInfoXMLAsync(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getHrmDepartmentInfoXML(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getHrmDepartmentInfoXMLAsync(string in0, string in1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HrmServicePortTypeChannel : TestTransaction.OAHrmServiceReference.HrmServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HrmServicePortTypeClient : System.ServiceModel.ClientBase<TestTransaction.OAHrmServiceReference.HrmServicePortType>, TestTransaction.OAHrmServiceReference.HrmServicePortType {
        
        public HrmServicePortTypeClient() {
        }
        
        public HrmServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HrmServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HrmServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HrmServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SynSubCompany(string in0, string in1) {
            return base.Channel.SynSubCompany(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> SynSubCompanyAsync(string in0, string in1) {
            return base.Channel.SynSubCompanyAsync(in0, in1);
        }
        
        public string getPropValue(string in0, string in1) {
            return base.Channel.getPropValue(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> getPropValueAsync(string in0, string in1) {
            return base.Channel.getPropValueAsync(in0, in1);
        }
        
        public string getHrmSubcompanyInfoXML(string in0) {
            return base.Channel.getHrmSubcompanyInfoXML(in0);
        }
        
        public System.Threading.Tasks.Task<string> getHrmSubcompanyInfoXMLAsync(string in0) {
            return base.Channel.getHrmSubcompanyInfoXMLAsync(in0);
        }
        
        public TestTransaction.OAHrmServiceReference.UserBean[] getHrmUserInfo(string in0, string in1, string in2, string in3, string in4, string in5) {
            return base.Channel.getHrmUserInfo(in0, in1, in2, in3, in4, in5);
        }
        
        public System.Threading.Tasks.Task<TestTransaction.OAHrmServiceReference.UserBean[]> getHrmUserInfoAsync(string in0, string in1, string in2, string in3, string in4, string in5) {
            return base.Channel.getHrmUserInfoAsync(in0, in1, in2, in3, in4, in5);
        }
        
        public TestTransaction.OAHrmServiceReference.DepartmentBean[] getHrmDepartmentInfo(string in0, string in1) {
            return base.Channel.getHrmDepartmentInfo(in0, in1);
        }
        
        public System.Threading.Tasks.Task<TestTransaction.OAHrmServiceReference.DepartmentBean[]> getHrmDepartmentInfoAsync(string in0, string in1) {
            return base.Channel.getHrmDepartmentInfoAsync(in0, in1);
        }
        
        public string getHrmUserInfoXML(string in0, string in1, string in2, string in3, string in4, string in5) {
            return base.Channel.getHrmUserInfoXML(in0, in1, in2, in3, in4, in5);
        }
        
        public System.Threading.Tasks.Task<string> getHrmUserInfoXMLAsync(string in0, string in1, string in2, string in3, string in4, string in5) {
            return base.Channel.getHrmUserInfoXMLAsync(in0, in1, in2, in3, in4, in5);
        }
        
        public bool checkUser(string in0, string in1, string in2) {
            return base.Channel.checkUser(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<bool> checkUserAsync(string in0, string in1, string in2) {
            return base.Channel.checkUserAsync(in0, in1, in2);
        }
        
        public TestTransaction.OAHrmServiceReference.JobTitleBean[] getHrmJobTitleInfo(string in0, string in1, string in2) {
            return base.Channel.getHrmJobTitleInfo(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<TestTransaction.OAHrmServiceReference.JobTitleBean[]> getHrmJobTitleInfoAsync(string in0, string in1, string in2) {
            return base.Channel.getHrmJobTitleInfoAsync(in0, in1, in2);
        }
        
        public bool changeUserPassword(string in0, string in1, string in2) {
            return base.Channel.changeUserPassword(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<bool> changeUserPasswordAsync(string in0, string in1, string in2) {
            return base.Channel.changeUserPasswordAsync(in0, in1, in2);
        }
        
        public TestTransaction.OAHrmServiceReference.anyType2anyTypeMap LoadTemplateProp(string in0) {
            return base.Channel.LoadTemplateProp(in0);
        }
        
        public System.Threading.Tasks.Task<TestTransaction.OAHrmServiceReference.anyType2anyTypeMap> LoadTemplatePropAsync(string in0) {
            return base.Channel.LoadTemplatePropAsync(in0);
        }
        
        public string SynDepartment(string in0, string in1) {
            return base.Channel.SynDepartment(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> SynDepartmentAsync(string in0, string in1) {
            return base.Channel.SynDepartmentAsync(in0, in1);
        }
        
        public void writeLog1(string in0, object in1) {
            base.Channel.writeLog1(in0, in1);
        }
        
        public System.Threading.Tasks.Task writeLog1Async(string in0, object in1) {
            return base.Channel.writeLog1Async(in0, in1);
        }
        
        public string SynJobtitle(string in0, string in1) {
            return base.Channel.SynJobtitle(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> SynJobtitleAsync(string in0, string in1) {
            return base.Channel.SynJobtitleAsync(in0, in1);
        }
        
        public void writeLog(object in0) {
            base.Channel.writeLog(in0);
        }
        
        public System.Threading.Tasks.Task writeLogAsync(object in0) {
            return base.Channel.writeLogAsync(in0);
        }
        
        public string getClientIpXfire() {
            return base.Channel.getClientIpXfire();
        }
        
        public System.Threading.Tasks.Task<string> getClientIpXfireAsync() {
            return base.Channel.getClientIpXfireAsync();
        }
        
        public string SynHrmResource(string in0, string in1) {
            return base.Channel.SynHrmResource(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> SynHrmResourceAsync(string in0, string in1) {
            return base.Channel.SynHrmResourceAsync(in0, in1);
        }
        
        public TestTransaction.OAHrmServiceReference.SubCompanyBean[] getHrmSubcompanyInfo(string in0) {
            return base.Channel.getHrmSubcompanyInfo(in0);
        }
        
        public System.Threading.Tasks.Task<TestTransaction.OAHrmServiceReference.SubCompanyBean[]> getHrmSubcompanyInfoAsync(string in0) {
            return base.Channel.getHrmSubcompanyInfoAsync(in0);
        }
        
        public string getHrmJobTitleInfoXML(string in0, string in1, string in2) {
            return base.Channel.getHrmJobTitleInfoXML(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<string> getHrmJobTitleInfoXMLAsync(string in0, string in1, string in2) {
            return base.Channel.getHrmJobTitleInfoXMLAsync(in0, in1, in2);
        }
        
        public string getHrmDepartmentInfoXML(string in0, string in1) {
            return base.Channel.getHrmDepartmentInfoXML(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> getHrmDepartmentInfoXMLAsync(string in0, string in1) {
            return base.Channel.getHrmDepartmentInfoXMLAsync(in0, in1);
        }
    }
}
